towny:
    # If true, LWC will only allow protections to be created inside of Towns via the Towny plugin
    townBorders: false

    # Protection cleanup options
    cleanup:
        # Should LWC remove protections when a plot is cleared?
        plotClear: false
        # Should LWC remove protections when the town is unclaimed?
        townUnclaim: false
        # Should LWC remove protections when a town goes to Ruin?
        townRuin: false
